### ISSUE TITLE
Remove constant in Bitcoin fee calculation

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1081]
We use a constant in `btc_signer.go` for the fee calculation:
https://github.com/zeta-chain/node/blob/60edc0e8b43ef44a014721740586b4345aa485c7/zetaclient/btc_signer.go#L63

However, in the bitcoin ZRC20 contract we read a `GAS_LIMIT` value to determine the tokens to burn for the fees.

There might be a discrepancy and if the value paid in the contract is lower than the value used for the actual tx, then it becomes a net loss for the tss signer.

**Comment by lumtis** [comment]
After having a look, we actually only use `estimateFee` for selecting UTXOs and not the effective fees.

However, in the code we use `txSize*gasPrice` for the fees which may result in a lower fees paid on ZetaChain if the ZRC20 `GasLimit` is not set high compared to the tx size.

We also adjust the fees if too low:
```
if fees.Int64() < int64(minFee*1e8) {
	fmt.Printf("fees %d is less than minFee %f; use minFee", fees, minFee*1e8)
	fees = big.NewInt(int64(minFee * 1e8))
}
```
Which can result in the same problem, a lower fee paid on ZetaChain

**Comment by brewmaster012** [comment]
yeah, gas fee in bitcoin might be tricky. I can see two problems:
1. our bitcoin outbound tx can be of variable size--zetacored does not know current UTXOs and cannot know exact size of the tx when scheduling. We could set a high size here as we have maximum 20 input UTXOs. 
2. how to deal with stuck tx due to low fee? RBF?

**Comment by lumtis** [comment]
Can be closed as we now use the gas limit for max tx size
