### ISSUE TITLE
ZetaClient might panic if signer is not found in signer map

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1643]
Signer is fetched in the signer map in `zetacore_observer` : https://github.com/zeta-chain/node/blob/d1236ba8e6660492b131e224c66c100490401c43/zetaclient/zetacore_observer.go#L184

It is not verified if existing, but still used: https://github.com/zeta-chain/node/blob/d1236ba8e6660492b131e224c66c100490401c43/zetaclient/zetacore_observer.go#L296

The panic is actually caused when the RPC is down (probably the signer entry is not created but still accessed)

We should:
- Replace the indexing of the map with chainID instead of the chain object for more reliability
- Verify signer existence
- Give a warning if a RPC is down

**Comment by ws4charlie** [comment]
The issue does not exist any more due to recent refactors.

- The index of map was already unified as `chainID` in the [Orchestrator](https://github.com/zeta-chain/node/blob/develop/zetaclient/orchestrator/orchestrator.go#L46) struct
- The existence of signer/observer is now checked [here](https://github.com/zeta-chain/node/blob/develop/zetaclient/orchestrator/orchestrator.go#L129) and [here](https://github.com/zeta-chain/node/blob/develop/zetaclient/orchestrator/orchestrator.go#L160)
- Error is printed if failed to `Dial` or `Ping` endpoint when creating observer/signer object in [here](https://github.com/zeta-chain/node/blob/develop/cmd/zetaclientd/utils.go#L141), [here](https://github.com/zeta-chain/node/blob/develop/cmd/zetaclientd/utils.go#L131), [here](https://github.com/zeta-chain/node/blob/develop/cmd/zetaclientd/utils.go#L90) and [here](https://github.com/zeta-chain/node/blob/develop/cmd/zetaclientd/utils.go#L100)
