### ISSUE TITLE
Investigate synchronized module versions and migration script

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1824]
This task is about checking and testing if we can make each ZetaChain module consensus version matching ZetaChain version and require migration script for each upgrade to reduce the risk of inconsistencies and wrong migration script run during an upgrade.

**Comment by lumtis** [comment]
@kingpinXD can we consider this PR on `develop`? https://github.com/zeta-chain/node/pull/1819
Did you check if the upgrade works correctly with this configuration?

**Comment by kingpinXD** [comment]
@lumtis  The upgrade does work with this configuration ,

I have been investigating a the upgrade module a little bit , and it seems like we have not been using the consensus versioning in the correct way .

Presently we do this 
`	for m, mb := range app.mm.Modules {
			vm[m] = mb.ConsensusVersion()
		}`
		
and then reduce the version for the modules we want to trigger updates for by 1 . 

It seems like we should not be doing the first step at all , since the upgrade keeper already has the consensus versions in state . It would only trigger the migration if the module-level consensus version was modified.

**Comment by lumtis** [comment]
We improved this part
