### ISSUE TITLE
Connector ZETA transfer failed on mainnet

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#2390]
https://zetachain.blockpi.network/lcd/v1/public/zeta-chain/crosschain/in_tx_hash_to_cctx_data/0x2d616107769f1426e097bde2def3858e5018b8c9e40563f86e265b4da41d91ad

Sending 71 ZETA from Ethereum to ZetaChain.

Status is:

```
feeInZeta(123524681859100658155) more than zetaBurnt (71843257882267442900)
```

**Comment by ilzheev** [comment]
Also, the second issue that I noticed is with refund destination.

Original Ethereum tx:
https://etherscan.io/tx/0x2d616107769f1426e097bde2def3858e5018b8c9e40563f86e265b4da41d91ad
<img width="788" alt="image" src="https://github.com/zeta-chain/node/assets/4902353/3c7c7525-f767-4392-9c88-0b8c81bb92c7">
- 71 ZETA sent from msg.sender `0x13...00FF` to Accumulated Finance contract `0x0A...38C0`
- Then these tokens sent from Accumulated Finance contract `0x0A...38C0` to ZetaConnector `0x00...7C6a`

But in ZetaChain explorer I noticed that "Revert to Ethereum" was set to the msg.sender instead of Accumulated Finance contract, that actually sent tokens to ZetaConnector:
<img width="588" alt="image" src="https://github.com/zeta-chain/node/assets/4902353/62c51092-7faf-4ca8-a6cd-2d813235026e">
https://explorer.zetachain.com/cc/tx/0x9e294481fda2b7c4bdd1f5c2cc17aee9e4297de1c5f82b705d4c2baad043d8e0

Can this logic be improved for future txs?
Otherwise there is a significant security risk of users infinite minting LST on sidechains (mint stZETA with ZETA, cross-chain tx failed, user got refunded with ZETA, rinse-repeat many times if cross-chain transfers keep failing due to any circumstances).

**Comment by fadeev** [comment]
> ZEVM Message Passing has not been enabled yet on Mainnet

> On the final error, it seems the ZETA amount is not sufficient to cover the revert tx. We need to check the liquidity ZETA/ETH pool, gas price might be higher than average

**Comment by fadeev** [comment]
@lumtis CCM gas fee from ZetaChain to Ethereum is 15.2, here the value (71) is clearly higher.

**Comment by lumtis** [comment]
> ZEVM Message Passing has not been enabled yet on Mainnet

This is planned to be performed soon.

> Can this logic be improved for future txs?
Otherwise there is a significant security risk of users infinite minting LST on sidechains (mint stZETA with ZETA, cross-chain tx failed, user got refunded with ZETA, rinse-repeat many times if cross-chain transfers keep failing due to any circumstances).

This is currently in consideration. We are in the process of designing new structure for system contract. One consideration is to provide a revert address when initiating a crosschain tx

> @lumtis CCM gas fee from ZetaChain to Ethereum is 15.2, here the value (71) is clearly higher.

We will investigate this further. Two possible paramater:
- The obversers apply a multiplier when voting the gas price for a transaction
- ZETAs are swapped into ETH for the revert fee payment. There might be a slight slippage involved

**Comment by ilzheev** [comment]
We temporarily disabled stZETA minting on sidechains, do you have ETA for the problem to be fixed? @fadeev @lumtis

**Comment by fadeev** [comment]
@lumtis shall we triage this? So that devs have better understanding when this will be shipped.

**Comment by lumtis** [comment]
> We temporarily disabled stZETA minting on sidechains, do you have ETA for the problem to be fixed? @fadeev @lumtis

Not defined yet. We are going to discuss about it in the team today

> @lumtis shall we triage this? So that devs have better understanding when this will be shipped.

https://github.com/zeta-chain/node/issues/2479

**Comment by lumtis** [comment]
Closing has we decided to not support Message Passing with ZEVM on mainnet. We have an issue to track supporting ZetaConnector with the gateway (that will enable the same interactions): https://github.com/zeta-chain/node/issues/3212
