### ISSUE TITLE
HAL 01: Zeta supply does not track assets correctly

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#564]
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/1352
- [ ] https://github.com/zeta-chain/node/issues/1353
- [ ] https://github.com/zeta-chain/node/issues/1354
- [ ] https://github.com/zeta-chain/node/issues/1355
```

**Comment by lumtis** [comment]
@kingpinXD can we break down into several tasks?

**Comment by CharlieMc0** [comment]
Is this completed? @lumtis @kingpinXD ?

**Comment by kingpinXD** [comment]
No, it's not 
The supply checker initially implemented was disabled as we planned to test it on Athens to determine the frequency of these checks so that the notifications are helpful. 

This would need to be prioritised / revisited to enable it backup again . Based on the current codebase , we would need to refactor the checking function

**Comment by lumtis** [comment]
We decided to go with monitoring + using emergency proposals

The previous ZetaClient implementation was bloated since requiring new queries and unclear process to report accounting issues.
There is no reason for ZetaClient to be in charge of this if emergency proposals are executed by external parties

What we should do is refactor to use a lock/unlock model for ZETA instead of mint/burn for non-Ethereum chians but we should first decide if we want to transition ZETA to the contract v2 model

**Comment by lumtis** [comment]
Closing in favor of https://github.com/zeta-chain/node/issues/881
