### ISSUE TITLE
Set higher priority for system and other important messages 

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/node#734]
An attacker or even high usage could prevent us from submitting important transactions like and emergency stop, changes to network parameters, TSS voting, etc 

Some message types may be more important than others and should have priority over them. That is, the more significant a message type is, the more quickly it should be included in a block, before other messages are.

Failing to prioritize message types allows attackers to front-run them, possibly gaining unfair advantage. Moreover, during high network congestion, the message may be simply not included in a block for a long period, causing the system to malfunction.

In the Cosmos's mempool, transactions are ordered in first-in-first-out (FIFO) manner by default. Especially, there is no fee-based ordering.

https://halborn.slack.com/files/U045CKR7ELE/F05BQ092R1S/cosmos_security_awareness_training.pdf

**Comment by lumtis** [comment]
Wouldn't setting a higher gas price for the important message fix the problem?

**Comment by lumtis** [comment]
It actually seems we will have to upgrade SDK to `0.47` for this: https://docs.cosmos.network/main/building-apps/app-mempool#priority-nonce-mempool

**Comment by lumtis** [comment]
Right now the only API we have in the SDK is the Context Priority value set in the AnteHandler.

The value is currently set to the lowest gas price in the tx:
https://github.com/cosmos/cosmos-sdk/blob/2154ce0bbe518744439bd4506e7afba3319ed459/x/auth/ante/validator_tx_fee.go#L54
While we could inject a hook that sets a high priority for admin messages, we shouldn't do this because the admin address check is stateful, therefore a spam admin message would need to go to the mempool before invalided.

The solution right now is to set a higher gas price.

**Comment by CharlieMc0** [comment]
Is priority-nonce-mempool different that the prioritized mempool available to use now? In the node config file there is option to switch between FIFO and prioritized. 

```
#######################################################
###          Mempool Configuration Option          ###
#######################################################
[mempool]

# Mempool version to use:
#   1) "v0" - (default) FIFO mempool.
#   2) "v1" - prioritized mempool.
version = "v0"
```

**Comment by lumtis** [comment]
It could be that `prioritized mempool` is what use https://github.com/cosmos/cosmos-sdk/blob/2154ce0bbe518744439bd4506e7afba3319ed459/x/auth/ante/validator_tx_fee.go#L54

and in this case we should use this.
