### ISSUE TITLE
Mechanism to automatically mitigate gas price hike

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#935]
### Problem

Chain gas prices are stored on-chain to determine the gas fees needed to be paid in order to pay the gas fees of an outbound chain during an outbound transaction.

The gas price is updated by an observer for a chain through the `MsgGasPriceVoter` message, the message update the gas price by calculating the median of the values provided by the observers.

For some networks, the gas price is not stable and might increase dramatically in a short period of time -- gas price hikes, which could result in a situation where the network just have the fund to pay for the outbound transaction gas fee or it doesn't know if the gas price should be increased, the txs are pending.

This issue is to discuss and determine a solution to mitigate gas price hikes:

**1. How to fund higher gas prices during hikes**
**2. How to determine if the gas price should be increased for a transaction**

### Funding gas price hikes

One of the possible mitigation is to create a stability pool (name to be determined) for each chain containing funds to compensate for the difference between the required gas price and the fees paid by the user.

`StabilityPool` is an address in the `fungible` module determined from the chain ID.

The `StabilityPool` is funded by the surplus of tokens paid by the user (currently `gasLimit * 2`) for an outbound transaction.

An additional mechanism to fund `StabilityPool` can be to define `StabilityFee` defined for each chains paid by the user specifically to fund the `StabilityPool`

The `StabilityFee` is set for each chain such as `GasPrice`, the value would differ depending on the stability of the network. The benefit of this method compared to using surplus from a multiple of `GasLimit` is that the fee can be determined depending on the stability of the network and would typically be lower for mainnet.

### Determine gas price hikes -- when an outbound tx must be resent

There must be a mechanism to determine when the gas price should be increased and funds from the `StabilityPool` used.

A typical solution can be to determine a pair of values
- `GasPriceIncreaseTimeLimit`
- `GasPriceIncreaseStep`
If the outbound transaction has not been mined after the delay `GasPriceIncreaseTimeLimit`, it is resent on the outbound network with a gas price increase by `GasPriceIncreaseStep`, funds from the `StabilityPool` are used to fund the additional gas. There should potentially be a limit when the gas price is not longer increased to not empty the stability pool in case of vary exceptionally high gas price.

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/node/issues/1044
- [ ] https://github.com/zeta-chain/node/issues/1045
- [ ] https://github.com/zeta-chain/node/issues/1046
- [ ] https://github.com/zeta-chain/node/issues/1048
```

**Comment by brewmaster012** [comment]
@lumtis a few comments about accounting: 
1. When confirming outbound txs, the state machine could look at the actual gas fee, and mint/burn the residual (burned gas in scheduling outbound - actual gas fee paid) to the StabilityPool. This is how StabilityPool is funded/expensed.

**Comment by lumtis** [comment]
> @lumtis a few comments about accounting:
> 
> 1. When confirming outbound txs, the state machine could look at the actual gas fee, and mint/burn the residual (burned gas in scheduling outbound - actual gas fee paid) to the StabilityPool. This is how StabilityPool is funded/expensed.

Yes, this is what I meant with

> The StabilityPool is funded by the surplus of tokens paid by the user (currently gasLimit * 2) for an outbound transaction.

The `StabilityFee` is the idea of an additional fee where the value would depend on the actual stability of the network

**Comment by lumtis** [comment]
I think the main first task would rely on the logic for resending outbound txs with a higher gas price. Pooling the current surplus that we have for the network should be trivial.

**Comment by kingpinXD** [comment]
For resending, it might be easier to concentrate the logic on the zeta-client and add a new value to the tracker to indicate the multiplier used for a particular tx hash. 
The tracker can be used when finalizing the outbound to manage accounting. 

Also , we can think of painting the stability pool on each external chain instead of Zetacore, in a way that the TSS address retains a fixed portion of the outbound TX, and thus automatically has funds to pay for stepping up the gas price when needed.

**Comment by brewmaster012** [comment]
@lumtis regarding resending outbound: there are two ways
1. modify the CCTX outbound gas price field. It gets automatically picked up in the next re-try. 
2. as @kingpinXD suggest implement the gas price logic in zetaclients. This might get a bit tricky because you want the zetaclients to arrive at the same gas price.

**Comment by lumtis** [comment]
> and make adjustment

Do you have ideas of the adjustment logic outside of defining an increment value? @brewmaster012

**Comment by brewmaster012** [comment]
@lumtis ,  I think we can probably make it quite simple
when we look at pending tx and decide to increase its gas price, we just increase it to slightly more than current gasprice. 

i would not worry about depleting stability pools too fast. If they are accounts on cosmos and EVM, then somebody can send some ZRC20 gas balance to the pools to top it up. 

THis might be necessary for testnet goerli, but for other chains and ethereum mainnet, since gas price is much more stable, i would worry even less about this. 

so my opinion would be to make the adjustment as simple and possible. Could be refined later if needed.

**Comment by lumtis** [comment]
> when we look at pending tx and decide to increase its gas price, we just increase it to slightly more than current gasprice.

Maybe we could think of a first implementation with 3 constants?
- `Epoch`: Number of blocks before the loop to check pending txs is executed in BeginBlock
- `ResendTime`: The amount of time before a tx is resent with a new gas price if still pending
- For each network: `Increment`: the value the gas price is increased when resent

**Comment by brewmaster012** [comment]
cool, that'll be great. I'd just want to say that the less parameter to tune the better in general. The `Increment` parameter seems to require a bit of tuning? 
But directionally i think this looks great.

**Comment by lumtis** [comment]
I was thinking of defining constants for now
