### ISSUE TITLE
Update the package name to `github.com/zeta-chain/node` to match the repo name

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#959]
Replace `github.com/zeta-chain/zetacore` with `github.com/zeta-chain/node` in `go.mod` and all the imports

**Comment by lumtis** [comment]
Hey @tantodefi , thanks for your interest in contributing.
Sounds good, assigning the issue to you, let us know if you have any questions.

**Comment by tantodefi** [comment]
So i updated the package name everywhere and i saw that on PR template i should run smoketest  but i got the following error:
 `panic: failed to query rpc: post failed: Post "http://zetacore0:26657": dial tcp x.x.x.x:26657: connect: connection refused` smoketest failing on macOS after updating package name in go.mod and all imports... any ideas?
i can test again later on ubuntu vm but curious if im missing something obvious like maybe its macos firewall issue?
```cctxClient.TSS error rpc error: code = NotFound desc = not found TSS not ready yet, waiting for TSS to be appear in zetacore netowrk...``` found in orchestrator log while running smoketest
Any feedback would be appreciated..

**Comment by lumtis** [comment]
Hi @tantodefi, the error might be related to a Dockerfile that depends on the name of a package but it is curious. It shouldn't happen because of the firewall because smoketest is fully local.
Maybe the logs of `zetacore0` container can help:
```
cd contrib/localnet
docker-compose logs zetacore0
```
If `zetacore0` is not started, it is definitely an issue with the Docker image
